FROM node:18-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_API_MAIN
ARG NEXT_PUBLIC_API_LIBRARY
ARG NEXT_PUBLIC_API_SIMPUL
ARG NEXT_PUBLIC_API_ADMISSION

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_MAIN=$NEXT_PUBLIC_API_MAIN
ENV NEXT_PUBLIC_API_LIBRARY=$NEXT_PUBLIC_API_LIBRARY
ENV NEXT_PUBLIC_API_SIMPUL=$NEXT_PUBLIC_API_SIMPUL
ENV NEXT_PUBLIC_API_ADMISSION=$NEXT_PUBLIC_API_ADMISSION

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

FROM node:18-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./

RUN npm install --production --legacy-peer-deps

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

EXPOSE 3000

CMD ["npm", "start"]
